/** Canonical lifecycle. Monetary amounts sent to providers are integer sen. */
export const ORDER_STATUSES = ['draft','docs_pending','payment_pending','payment_review','payment_confirmed','admin_review','submitted_to_jpjeplate','in_production','arrived_workshop','appointment_scheduled','installation_proof_pending','installed','rejected','cancelled'] as const;
export type CanonicalOrderStatus = typeof ORDER_STATUSES[number];
export type AppRole = 'customer' | 'operator' | 'admin' | 'installer';
export const PRICE_MYR = 150;
export const CURRENCY = 'MYR';
export const TIME_ZONE = 'Asia/Kuala_Lumpur';
export const STATUS_LABELS: Record<CanonicalOrderStatus,string> = {draft:'Draft',docs_pending:'Documents required',payment_pending:'Payment required',payment_review:'Payment being checked',payment_confirmed:'Payment confirmed',admin_review:'Order under review',submitted_to_jpjeplate:'Submitted to JPJePlate',in_production:'In production',arrived_workshop:'Ready for appointment',appointment_scheduled:'Appointment confirmed',installation_proof_pending:'Installation in progress',installed:'Installation completed',rejected:'Action required',cancelled:'Cancelled'};
export const TRANSITIONS: Record<CanonicalOrderStatus, readonly CanonicalOrderStatus[]> = {draft:['docs_pending','cancelled'],docs_pending:['payment_pending','admin_review','rejected','cancelled'],payment_pending:['payment_review','payment_confirmed','cancelled'],payment_review:['payment_confirmed','cancelled'],payment_confirmed:['admin_review'],admin_review:['submitted_to_jpjeplate','docs_pending','rejected','cancelled'],submitted_to_jpjeplate:['in_production'],in_production:['arrived_workshop'],arrived_workshop:['appointment_scheduled'],appointment_scheduled:['installation_proof_pending'],installation_proof_pending:['installed'],installed:[],rejected:['docs_pending','cancelled'],cancelled:[]};
export function canTransition(from: CanonicalOrderStatus,to: CanonicalOrderStatus,role:AppRole):boolean { return TRANSITIONS[from].includes(to) && (role==='admin'||role==='operator'||(role==='customer'&&['draft','docs_pending','rejected'].includes(from)&&['docs_pending','payment_pending','admin_review','cancelled'].includes(to))||(role==='customer'&&((from==='arrived_workshop'&&to==='appointment_scheduled')||(['payment_pending','payment_review'].includes(from)&&to==='cancelled')))||(role==='installer'&&['installation_proof_pending','installed'].includes(to))); }
export const formatMYR = (value:number) => new Intl.NumberFormat('en-MY',{style:'currency',currency:CURRENCY}).format(value);
